site_name: "Datacraft Framework"

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
            show_signature: true
            show_root_heading: true
            show_bases: true
            show_submodules: true
            members_order: source
            filters: "!^_"
            inherited_members: true
            docstring_style: google
            annotations_path: brief

  - autorefs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - "Get Started": index.md
  - "Code Documentation":
      - "Common":
          - "JsonData Mapper": Common/JsonDataMapper.md
          - "FileName Generator": Common/FileNameGenerator.md
          - "Orchestration Process": Common/OrchestrationProcess.md
          - "Pattern Validator": Common/PatternValidator.md
          - "S3 Process": Common/S3Process.md
          - "Regex Date Formats": Common/RegexDateFormats.md
          - "Schema Caster": Common/SchemaCaster.md
          - "Data Processor": Common/DataProcessor.md

      - "Extractors - Bronze Layer Scripts":
          - "Api Extractor": Extractors/ApiExtractor.md
          - "Database Extractor": Extractors/DatabaseExtractor.md
          - "S3 Extractor": Extractors/S3Extractor.md
          - "Salesforce Extractor": Extractors/SalesforceExtractor.md
          - "SFTP Extractor": Extractors/SftpExtractor.md

      - "Silver LayerScripts":
          - "Data Standardization": SilverLayerScripts/DataStandardization.md
          - "Data Quality Check": SilverLayerScripts/DataQualityCheck.md
